kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - go fmt  ./...
      - go vet  ./...
      - golangci-lint run

  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t gitea.dancheg97.ru/drone/$DRONE_REPO:latest -t gitea.dancheg97.ru/dancheg97/$DRONE_REPO:$(date +"%m-%d-%y") .
      - docker login -u drone -p password
      - docker push gitea.dancheg97.ru/drone/$DRONE_REPO:latest
      - docker push gitea.dancheg97.ru/drone/$DRONE_REPO:$(date +"%m-%d-%y")
