kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint and test
    image: dancheg97.ru/templates/gen-tools:latest
    commands:
      - go fmt  ./...
      - go vet  ./...
      - golangci-lint run
      - buf lint
      - go test ./...

  - name: build and push docker registry
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PASS:
        from_secret: PASS
    commands:
      - docker build -t dancheg97.ru/$DRONE_REPO:latest -t dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y") .
      - docker login -u dancheg97 -p $PASS dancheg97.ru
      - docker push dancheg97.ru/$DRONE_REPO:latest
      - docker push dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y")

  - name: push github mirror
    image: appleboy/drone-git-push
    settings:
      branch: master
      remote: ssh://git@github.com/dancheg97/go-pacman.git
      force: false
      commit: true
      ssh_key:
        from_secret: SSHKEY
