kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint and test
    image: golangci/golangci-lint:latest
    commands:
      - go fmt  ./...
      - go vet  ./...
      - golangci-lint run
      - go test ./...

  - name: build and push docker registry
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PASS:
        from_secret: PASS
    commands:
      - docker build -t dancheg97.ru/$DRONE_REPO:latest
      - docker login -u dancheg97 -p $PASS dancheg97.ru
      - docker push dancheg97.ru/$DRONE_REPO:latest

  - name: push github mirror
    image: appleboy/drone-git-push
    settings:
      branch: main
      remote: git@github.com:ctlos/ctlpkg.git
      force: false
      commit: true
      ssh_key:
        from_secret: SSHKEY
