kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

steps:
  - name: lint
    image: gitea.dancheg97.ru/templates/golden-go:latest
    commands:
      - go fmt  ./...
      - go vet  ./...
      - golangci-lint run
      - buf lint

  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t gitea.dancheg97.ru/$DRONE_REPO:latest -t gitea.dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y") .
  
  - name: push
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    environment:
      PASS:
        from_secret: PASS
    commands:
      - docker login -u dancheg97 -p $PASS gitea.dancheg97.ru
      - docker push gitea.dancheg97.ru/$DRONE_REPO:latest
      - docker push gitea.dancheg97.ru/$DRONE_REPO:$(date +"%m-%d-%y")
