kind: pipeline
name: default
type: docker

trigger:
  branch:
    - main

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

services:
  - name: postgres
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

steps:
  - name: lint
    image: golangci/golangci-lint
    commands:
      - go fmt  ./...
      - go vet  ./...
      - golangci-lint run

  - name: test
    image: golang
    environment:
      POSTGRES_CONN_STRING: postgresql://user:password@postgres:5432/db
      GRPC_PORT: 9080
    commands:
      - go run . migrate
      - go test -short -count=1 -cover ./...

  - name: build
    image: docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    commands:
      - docker build -t $DRONE_REPO:latest -t $DRONE_REPO:$(date +"%m-%d-%y") .
