version: "3.11"

services:
  app:
    build:
      context: .
    command: run
    environment:
      CTLPKG_INIT_PKGS: adw-gtk-theme gnome-browser-connector gnome-shell-extension-dash-to-dock zsh-theme-powerlevel10k-bin-git zsh-autosuggestions zsh-syntax-highlighting ttf-meslo-nerd-font-powerlevel10k
      CTLPKG_LOGS_FORMAT: text
      CTLPKG_LOGINS: user|password
    ports:
      - 8080:8080
