version: "3.11"

services:
  app:
    build:
      context: .
    environment:
      FMNXREPO_INIT_PKGS: yay
      FMNXREPO_LOGS_FORMAT: text
      FMNXREPO_LOGINS: dev|hehehe
    ports:
      - 8080:8080
