version: "3.11"

services:
  app:
    build:
      context: .
    environment:
      FMNXREPO_REPO: localhost
      FMNXREPO_PORT: 80
      FMNXREPO_API_ADRESS: http://localhost/
      FMNXREPO_LOGS_FORMAT: text
      FMNXREPO_LOGINS: dev|hehehe
    ports:
      - 80:80
