version: "3.11"

services:
  app:
    build:
      context: .
    command: run
    environment:
      CTLPKG_INIT_PKGS:  yay
      CTLPKG_LOGS_FORMAT: text
      CTLPKG_LOGINS: user1|pass1|user2|pass2
    ports:
      - 8080:8080
