version: '3.8'

services:
  app:
    build:
      context: .
    command: run
    environment:
      POSTGRES_CONN_STRING: postgresql://user:password@postgres:5432/db
      GRPC_PORT: 9080
    ports:
      - 9080:9080
    depends_on:
      migrator:
        condition: service_completed_successfully

  migrator:
    build:
      context: .
    command: migrate
    volumes:
      - ./migrations:/migrations
    environment:
      MIGR_CONN_STR: postgresql://user:password@postgres:5432/db
      MIGRATIONS_DIR: migrations/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 1s
      retries: 5
    ports:
      - 7000:5432
