name: repo
description: Container package repository.

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  provider: ^6.0.5
  data_table_2: ^2.0.3
  protobuf: ^2.1.0
  grpc: ^3.1.0
  flutter_shake_animated: ^0.0.5
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.20
  file_picker: ^5.2.9
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
